DTYPE: "float32"

INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1280
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1280
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  TO_BGR255: False

  # This augmentation is intended for dataset with small motion.
  MOTION_LIMIT: 0.1
  MOTION_BLUR_PROB: 1.0
  COMPRESSION_LIMIT: 50
  BRIGHTNESS: 0.1
  CONTRAST: 0.1
  SATURATION: 0.1
  HUE: 0.1

  AMODAL: True

VIDEO:
   TEMPORAL_WINDOW: 1000
   TEMPORAL_SAMPLING: 1000
   RANDOM_FRAMES_PER_CLIP: 2

MODEL:
  BOX_ON: True
  TRACK_ON: True

  BACKBONE:
    CONV_BODY: "DLA-34-FPN"
  
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 300
    FPN_POST_NMS_TOP_N_TEST: 300
  
  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 32
  
  # Box branch configuration
  ROI_BOX_HEAD:
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    NUM_CLASSES: 2  # Change it back to 10 classes when using "person-vehicle".
  
  TRACK_HEAD:
    NMS_THRESH: 0.5
    MAX_DORMANT_FRAMES: 50
    SOLVER_TYPE: 'ext_reid'
    ADD_DEBUG: True
    FREEZE_DORMANT: True
  
SOLVER:
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.0001
  STEPS: (5000, 7000)
  MAX_ITER: 10000
  VIDEO_CLIPS_PER_BATCH: 2
  CHECKPOINT_PERIOD: 500

DATASETS:
  # SET THIS PATH CORRECTLY
  ROOT_DIR: "E:/datasets"
  TRAIN: ("UA_DETRAC",)

DATALOADER:
  ASPECT_RATIO_GROUPING: False
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 3
